language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
 apt:
   packages:
   - python-pip

install:
 # Install ansible
 - pip install ansible

 # Check ansible version
 - ansible --version

 - git clone https://github.com/JieJhih/ansible-minio.git
 - cd ansible-minio

script:
 # Basic role syntax check
 - ansible-playbook install.yml --extra-vars "variable_host=localhost"
 - docker ps -a